apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: allocation-manager
  namespace: offender-management-preprod
spec:
  selector:
    matchLabels:
      app: allocation-manager
  namespaceSelector:
    matchNames:
    - offender-management-preprod
  endpoints:
  - port: metrics
    interval: 15s
