defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        RAILS_ENV: test
        RACK_ENV: test

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - allocation-manager-v1-{{ checksum "Gemfile.lock" }}
            - allocation-manager-v1-
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install GOV.UK frontend modules
          command: npm install
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: allocation-manager-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
            - node_modules/

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bundle --path vendor/bundle
      - run:
          name: Download Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rake
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

  security-static-analysis:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bundle --path vendor/bundle
      - run: bundle exec brakeman -o brakeman.html
      - store_artifacts:
          path: brakeman.html

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - security-static-analysis:
          requires:
            - build
