apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: offender-manager-process-movements
spec:
  schedule: "0 2 * * *"
  startingDeadlineSeconds: 10
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: process-movements
            image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/offender-management/offender-management-allocation-manager:latest
            imagePullPolicy: Always
            command: ['sh', '-c', "bundle exec rake movements:process"]
          restartPolicy: OnFailure
