apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: allocation-manager
 namespace: offender-management-production
 annotations:
   kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - allocation-manager-production.apps.live-1.cloud-platform.service.justice.gov.uk
  - hosts:
    - moic.service.justice.gov.uk
    secretName: allocation-manager-hostname
  rules:
  - host: allocation-manager-production.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: allocation-manager
          servicePort: 3000
  - host: moic.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: allocation-manager
          servicePort: 3000
