apiVersion: batch/v1
kind: Job
metadata:
  name: rails-migrations
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: allocation-manager
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/offender-management/offender-management-allocation-manager:latest
        command: [ 'sh', '-c', 'bundle exec rails db:migrate']
        envFrom:
          - configMapRef:
              name: shared-environment
          - secretRef:
              name: allocation-manager-secrets
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: rds_instance_address
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: postgres_password
          - name: POSTGRES_NAME
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: postgres_name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: postgres_user
      restartPolicy: OnFailure
