apiVersion: batch/v1
kind: Job
metadata:
  name: rails-migrations
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: rails-app
        image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/davids-dummy-team/davids-dummy-app:rails-app-1.0
        command: [ 'sh', '-c', 'bundle exec rails db:migrate && bundle exec rails db:seed']
        envFrom:
          - configMapRef:
              name: shared-environment
          - secretRef:
              name: allocation-manager-secrets
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: rds_instance_address
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: postgres_password
          - name: POSTGRES_NAME
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: postgres_name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: allocation-rds-instance-output
                key: postgres_user
      restartPolicy: OnFailure
